language: scala
sudo: false
jdk: oraclejdk8
dist: trusty
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/launchers"
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
jobs:
  include:
    - stage: test
      script: sbt test
      name: tests
    - name: helm chart
      script:
        - ./scripts/lint_chart.sh
        - ./scripts/package_chart.sh
