apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "kafka-lag-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-lag-exporter.name" . }}
    helm.sh/chart: {{ include "kafka-lag-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka-lag-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Value.podAnnotations | indent 8 }}
      {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kafka-lag-exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if or .Values.watchers.strimzi .Values.serviceAccount.create }}
      serviceAccountName: {{ include "kafka-lag-exporter.fullname" . }}-serviceaccount
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: []
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config-volume
              mountPath: /opt/docker/conf/
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "kafka-lag-exporter.fullname" . }}-configmap
